#!/bin/bash
set +u
# package.sh
# MIT No Attribution
#
# Copyright 2025 Matthew Conroy
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

print_usage() {
  cat <<EOF
==============
Lab Template
==============
Quick usage guide:

1. Modify the variables in config.sh
2. Replace the contents of source/source.c with the contents of your program.
3. Add in any relevant files into source/
4. Place a relevant screenshot or image into the screenshots/ directory
5. Run package.sh

Your generated zip file will be present in the output folder.

See README for more detailed information.
==============
EOF
}

# == Utility functions ==
# Ask for confirmation before continuing
confirm() {
  echo -n "Continue? (y/n): "
  read answer
  if [ "$answer" = "y" ]; then
    return 0
  else
    cleanup
    exit 1
  fi
}

# Delete temporary files
cleanup() {
  if [ -z "${TEMP_DIR}" ]; then
    echo "ERROR: Attempted cleanup, but TEMP_DIR is unset!"
    exit 1
  fi

  log "Removing temp files"
  rm -r "${TEMP_DIR}"
  rm "${LATEX_DIR}images.tex"
  rm "${LATEX_DIR}title.tex"
  return 0
}

log() {
  if [ -z "${NO_LOGS}" ]; then
    echo "[package.sh] $@"
  fi
}
# == ==

# Load config if main variables are not defined
if [ -z "${NAME:-}" ] && [ -z "${STUDENT_ID:-}" ]; then
  source config.sh
fi

# --- help argument and setup ---
if [ "$1" == "--help" ] || [ "$1" == "-help" ]; then
  print_usage
  exit 0
fi

if [ -z "${NAME}" ]; then
  echo "ERROR: Varible NAME is unset"
  print_usage
  exit 1
fi
if [ -z "${STUDENT_ID}" ]; then
  echo "ERROR: Varible STUDENT_ID is unset"
  print_usage
  exit 1
fi

if [ -z "${TITLE}" ]; then
  export TITLE="Assignment"
fi
if [ -z "${LATEX_TITLE}" ]; then
  LATEX_TITLE="${TITLE}"
  log "Set LATEX_TITLE to TITLE"
fi
if [ -z "${LATEX_NAME}" ]; then
  LATEX_NAME="${NAME}"
  log "Set LATEX_NAME to NAME"
fi
if [ -z "${TEMP_CLEANUP}" ]; then
  TEMP_CLEANUP=1
  log "Set TEMP_CLEANUP to 1"
fi
if [ -z "${INCLUDE_FULL_SOURCE}" ]; then
  INCLUDE_FULL_SOURCE=1
  log "Set INCLUDE_FULL_SOURCE to 1"
fi

if [ -z "${DATE}" ]; then
  DATE="$(date +%d/%m/%Y)"
  log "Set DATE to ${DATE}"
fi

TEMP_DIR_NAME="temp"
TEMP_DIR="${TEMP_DIR_NAME}/"
PACKAGE_NAME="${TITLE}_${NAME}_${STUDENT_ID}_Submission"
PACKAGE_DIR="${TEMP_DIR}${PACKAGE_NAME}/"
SOURCE_DIR="source/"
LATEX_DIR="latex/"
SCREENSHOT_DIR="screenshots/"
OUTPUT_DIR="output/"

LATEX_GENERATED_MESSAGE="%generated by package.sh"

log "Making Directories"
mkdir -p "${TEMP_DIR}" || exit $?
mkdir -p "${PACKAGE_DIR}" || exit $?
mkdir -p "${PACKAGE_DIR}${SCREENSHOT_DIR}" || exit $?
mkdir -p "${SCREENSHOT_DIR}" || exit $?

# Smoke test the source file
log "Testing: ${SOURCE_DIR}source.c"
if ./smoke_test.sh; then
  SMOKE_TEST="SUCCESS"
else
  SMOKE_TEST="FAILED"
  confirm
fi

#Generate info header in the source.c file
SOURCE_C_GEN_FILE="${PACKAGE_DIR}source.c"
log "Generating: ${SOURCE_C_GEN_FILE}"
echo "/*" >"${SOURCE_C_GEN_FILE}"
echo "NAME      : ${NAME}" >>"${SOURCE_C_GEN_FILE}"
echo "STUDENT ID: ${STUDENT_ID}" >>"${SOURCE_C_GEN_FILE}"
echo "DATE      : ${DATE}" >>"${SOURCE_C_GEN_FILE}"
echo "*/" >>"${SOURCE_C_GEN_FILE}"
cat "${SOURCE_DIR}source.c" >>"${SOURCE_C_GEN_FILE}"

if [ ${INCLUDE_FULL_SOURCE} -eq 1 ]; then
  # Go over every file except source, and add it to the temp directory for packaging
  for file in "${SOURCE_DIR}"*; do
    if [[ "$(basename "$file")" == "source.c" ]]; then
      continue
    fi
    cp -r "$file" "${PACKAGE_DIR}"
  done
fi

#Generate latex file for the tile
TITLE_TEX_FILE="${LATEX_DIR}title.tex"
log "Generating: ${TILTE_TEX_FILE}"
echo "${LATEX_GENERATED_MESSAGE}" >"${TITLE_TEX_FILE}"
echo "\title{${LATEX_TITLE}}" >>"${TITLE_TEX_FILE}"
echo "\author{${LATEX_NAME}}" >>"${TITLE_TEX_FILE}"
echo "\date{${DATE}}" >>"${TITLE_TEX_FILE}"
echo "\newcommand\thestudentid{${STUDENT_ID}}" >>"${TITLE_TEX_FILE}"

#loop over every file in the ss dir and generate a images.tex
IMAGES_TEX_FILE="${LATEX_DIR}images.tex"
log "Generating: ${IMAGES_TEX_FILE}"
echo "${LATEX_GENERATED_MESSAGE}" >"${IMAGES_TEX_FILE}"
for file in "$SCREENSHOT_DIR"/*; do
  MIME_TYPE="$(file "${file}" -b --mime-type)"
  if [[ "${MIME_TYPE}" != image* ]]; then
    continue
  fi
  log "Processing: ${file}"
  TEX_PRE="${file%.*}_pre.tex"
  TEX_POST="${file%.*}_post.tex"
  if [ -f "${TEX_PRE}" ]; then
    log "    appending prefix: ${TEX_PRE}"
    cat "${TEX_PRE}" >>"${IMAGES_TEX_FILE}"
  fi
  echo "\includegraphics[width=\textwidth]{${file}}" >>"${IMAGES_TEX_FILE}"

  if [ -f "${TEX_POST}" ]; then
    log "    appending postfix: ${TEX_POST}"
    cat "${TEX_POST}" >>"${IMAGES_TEX_FILE}"
  fi

  cp "${file}" "${PACKAGE_DIR}${SCREENSHOT_DIR}"
done

DOC_TITLE="${TITLE}_${NAME}_${STUDENT_ID}"
log "Creating (with pandoc): ${PACKAGE_DIR}${DOC_TITLE}.docx"
pandoc "${LATEX_DIR}doc.tex" --output "${PACKAGE_DIR}${DOC_TITLE}.docx" || exit $?
#I hate pdflatex
log "Creating (with pdflatex): ${PACKAGE_DIR}${DOC_TITLE}.pdf"
pdflatex -interaction=nonstopmode -output-directory="${TEMP_DIR_NAME}" "${LATEX_DIR}doc.tex" || exit $?
cp "${TEMP_DIR}doc.pdf" "${PACKAGE_DIR}${DOC_TITLE}.pdf" || exit $?

log "Creating (with zip): ${TITLE}.zip"

cd "${TEMP_DIR}" || exit $?
zip --recurse-paths "${PACKAGE_NAME}.zip" "${PACKAGE_NAME}" || exit $?
cd ..
mv "${TEMP_DIR}${PACKAGE_NAME}.zip" "${OUTPUT_DIR}"

# Final report

if [ ${TEMP_CLEANUP} -eq 1 ]; then
  cleanup
fi

cat <<EOF

==============
Complete!
==============
Temp files removed: $([ "${TEMP_CLEANUP}" -eq 1 ] && echo "TRUE" || echo "FALSE")
Full source folder included: $([ "${INCLUDE_FULL_SOURCE}" -eq 1 ] && echo "TRUE" || echo "FALSE")
Assignment title: ${TITLE}
Date: ${DATE}
Student ID: ${STUDENT_ID}
Student Name: ${NAME}

Smoke test status: ${SMOKE_TEST} 
^^^^^^^^^^ You can ignore this if your program needs specific compilation flags or doesn't work for the standard specified in config.sh

The complete assignment archive is in the output folder.
Location: ${OUTPUT_DIR}${PACKAGE_NAME}.zip
==============
EOF
