#!/bin/bash

# package.sh
# MIT No Attribution
#
# Copyright 2025 Matthew Conroy
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

print_usage() {
  cat <<EOF
Lab Template
==============
Quick usage guide:

1. Modify the variables in config.sh
2. Replace the contents of source.c with the contents of your program.
3. Place a relevant screenshot or image into the screenshots/ directory
4. Run package.sh

See README for more detailed information.
==============
EOF
}

# Ask for confirmation before continuing
confirm() {
  echo -n "Continue? (y/n): "
  read answer
  if [ "$answer" = "y" ]; then
    return 0
  else
    cleanup
    exit 1
  fi
}

# Delete temporary files
cleanup() {
  return 0
}

log() {
  if [ -z "${NO_LOGS}" ]; then
    echo "[package.sh] $@"
  fi
}

# Load config if no arguments
if [ $# -eq 0 ]; then
  source config.sh
fi

# --- help argument and setup ---
if [ "$1" == "--help" ] || [ "$1" == "-help" ]; then
  print_usage
  exit 0
fi

if [ -z "${NAME}" ]; then
  echo "ERROR: Varible NAME is unset"
  print_usage
  exit 1
fi
if [ -z "${STUDENT_ID}" ]; then
  echo "ERROR: Varible STUDENT_ID is unset"
  print_usage
  exit 1
fi

if [ -z "${TITLE}" ]; then
  export TITLE="Assignment"
fi
if [ -z "${LATEX_TITLE}" ]; then
  LATEX_TITLE="${TITLE}"
fi
if [ -z "${LATEX_NAME}" ]; then
  LATEX_NAME="${NAME}"
fi

if [ -z "${DATE}" ]; then
  DATE="$(date +%d/%m/%Y)"
fi

PACKAGE_NAME="${TITLE}_${NAME}_${STUDENT_ID}_Submission"
PACKAGE_DIR="${PACKAGE_NAME}/"
SOURCE_DIR="source/"
LATEX_DIR="latex/"
TEMP_DIR_NAME="temp"
TEMP_DIR="${TEMP_DIR_NAME}/"
SCREENSHOT_DIR="screenshots/"

LATEX_GENERATED_MESSAGE="%generated by package.sh"

log "Making Directories"
mkdir -p "${PACKAGE_DIR}" || exit $?
mkdir -p "${PACKAGE_DIR}${SCREENSHOT_DIR}" || exit $?
mkdir -p "${SCREENSHOT_DIR}" || exit $?
mkdir -p "${TEMP_DIR}" || exit $?

# Smoke test the source file
log "Testing: ${SOURCE_DIR}source.c"
if ./smoke_test.sh; then
  echo "Primative smoke test succeeded."
else
  echo "Primative smoke test failed."
  confirm
fi

#Generate info header in the source.c file
SOURCE_C_GEN_FILE="${PACKAGE_DIR}source.c"
log "Generating: ${SOURCE_C_GEN_FILE}"
echo "/*" >"${SOURCE_C_GEN_FILE}"
echo "NAME      : ${NAME}" >>"${SOURCE_C_GEN_FILE}"
echo "STUDENT ID: ${STUDENT_ID}" >>"${SOURCE_C_GEN_FILE}"
echo "DATE      : ${DATE}" >>"${SOURCE_C_GEN_FILE}"
echo "*/" >>"${SOURCE_C_GEN_FILE}"
cat "${SOURCE_DIR}source.c" >>"${SOURCE_C_GEN_FILE}"

#Generate latex file for the tile
TITLE_TEX_FILE="${LATEX_DIR}title.tex"
log "Generateing: ${TILTE_TEX_FILE}"
echo "${LATEX_GENERATED_MESSAGE}" >"${TITLE_TEX_FILE}"
echo "\title{${LATEX_TITLE}}" >>"${TITLE_TEX_FILE}"
echo "\author{${LATEX_NAME}}" >>"${TITLE_TEX_FILE}"
echo "\date{${DATE}}" >>"${TITLE_TEX_FILE}"
echo "\newcommand\thestudentid{${STUDENT_ID}}" >>"${TITLE_TEX_FILE}"

#loop over every file in the ss dir and generate a images.tex
IMAGES_TEX_FILE="${LATEX_DIR}images.tex"
log "Generating: ${IMAGES_TEX_FILE}"
echo "${LATEX_GENERATED_MESSAGE}" >"${IMAGES_TEX_FILE}"
for file in $SCREENSHOT_DIR/*; do
  MIME_TYPE="$(file "${file}" -b --mime-type)"
  if [[ "${MIME_TYPE}" != image* ]]; then
    continue
  fi
  log "Processing: ${file}"
  TEX_PRE="${file%.*}_pre.tex"
  TEX_POST="${file%.*}_post.tex"
  if [ -f "${TEX_PRE}" ]; then
    log "    appending prefix: ${TEX_PRE}"
    cat "${TEX_PRE}" >>"${IMAGES_TEX_FILE}"
  fi
  echo "\includegraphics[width=\textwidth]{${file}}" >>"${IMAGES_TEX_FILE}"

  if [ -f "${TEX_POST}" ]; then
    log "    appending postfix: ${TEX_POST}"
    cat "${TEX_POST}" >>"${IMAGES_TEX_FILE}"
  fi

  cp "${file}" "${PACKAGE_DIR}${SCREENSHOT_DIR}"
done

DOC_TITLE="${TITLE}_${NAME}_${STUDENT_ID}"
log "Creating (with pandoc): ${PACKAGE_DIR}${DOC_TITLE}.docx"
pandoc "${LATEX_DIR}doc.tex" --output "${PACKAGE_DIR}${DOC_TITLE}.docx" || exit $?
#I hate pdflatex
log "Creating (with pdflatex): ${PACKAGE_DIR}${DOC_TITLE}.pdf"
pdflatex -interaction=nonstopmode -output-directory="${TEMP_DIR_NAME}" "${LATEX_DIR}doc.tex" || exit $?
cp "${TEMP_DIR}doc.pdf" "${PACKAGE_DIR}${DOC_TITLE}.pdf" || exit $?

log "Creating (with zip): ${TITLE}.zip"
zip --recurse-paths "${PACKAGE_NAME}.zip" "${PACKAGE_DIR}" || exit $?
